version: '3.8'

services:
  backend:
    container_name: interact-mailer
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8008:${PORT}
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs/