version: '3.8'

services:
  backend:
    container_name: interact-mailer
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8008:${PORT}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs/
    networks:
      - interact_go_backend-network

networks:
  interact_go_backend-network:
    external: true